feat: added custom session replication prototype
vaadin/azure-kit pull request #20
Opened 2022-10-27 09:39 UTC by mcollovati

Adds custom components for session replication from kubernetes-scaling repo.
Autoconfiguration has been refactored to activate this feature only if spring-session is not present

2022-10-27 10:46 UTC, mcollovati commented
Demo application work with custom session replication on local cluster.
Tests still missing

2022-10-28 06:45 UTC, MatthewVaadin requested changes

2022-10-28 06:45 UTC, MatthewVaadin commented on azure-kit-demo/pom.xml
> +                <!--
Remove commented code

2022-10-28 07:51 UTC, mcollovati commented on azure-kit-demo/pom.xml
> +                <!--
done

2022-10-28 07:57 UTC, MatthewVaadin approved these changes

2022-10-31 07:57 UTC, MatthewVaadin requested changes
Add tests and JavaDoc for new classes

2022-11-02 06:15 UTC, MatthewVaadin commented on azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/backend/RedisConnector.java
> +    void setRedisConnectionFactory(RedisConnectionFactory redisConnectionFactory) {
I'm not sure how to change these lines in `AzureKitConfiguration` if we do that:
```java
@Bean
@ConditionalOnBean(RedisConnectionFactory.class)
RedisConnector redisConnector() {
    return new RedisConnector();
}
```

2022-11-02 08:40 UTC, mcollovati commented on azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/backend/RedisConnector.java
> +    void setRedisConnectionFactory(RedisConnectionFactory redisConnectionFactory) {
This should work
```
@Bean
@ConditionalOnBean(RedisConnectionFactory.class)
RedisConnector redisConnector(RedisConnectionFactory factory) {
    return new RedisConnector(factory);
}
```

2022-11-02 09:11 UTC, MatthewVaadin approved these changes

2022-11-02 09:22 UTC, merged

2022-11-02 11:52 UTC, heruan reviewed
There are still missing tests and JavaDoc, see https://github.com/vaadin/azure-kit/issues/28